#!/usr/bin/eve python
# Author ID: jkbrar14

def calculate_age  (birth_year):
  current_year = 2023
	age = current_year - bith_year
	return age

birth_year = int(input("Put down rhe year you were born:"))
age = calculate_age(birth_year)
print("Your age is:"age)

def helloWorld():
	print(‘Hello World’)


helloWorld()
